version: "3.8"
services:
    group_server:
        build: .
        ports:
            - "8082:8080"
        env_file:
            - ./envs/.env.production
        networks:
            - group
            - default

    group_postgres:
        image: "postgres"
        ports:
            - "5434:5432"
        env_file:
            - ../.db.auth.docker.env
        volumes:
            - "group_data:/var/lib/postgresql/data"
        networks:
            - group
            - default
networks:
    default:
        external:
            name: messageQ
        driver: bridge
    group:
        external: true
        driver: bridge

volumes:
    group_data:
