apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  name: group-postgres-hs
  labels: 
    postgres: group
spec:
  ports:
    - port: 5566
      name: hs-port
  clusterIP: None
  selector:
    postgres: group
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  # creationTimestamp: null
  labels:
    io.kompose.service: group-postgres
  name: group-postgres
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: group-postgres
  serviceName: group-postgres-hs
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      # creationTimestamp: null
      labels:
        # io.kompose.network/group: "true"
        # io.kompose.network/message-q: "true"
        postgres: group
        io.kompose.service: group-postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DATABASE
                  name: db-auth-docker-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: db-auth-docker-env
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: db-auth-docker-env
          image: postgres
          name: group-postgres
          ports:
            - containerPort: 5432
            - containerPort: 5566
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: group-data
      restartPolicy: Always
      volumes:
        - name: group-data
          persistentVolumeClaim:
            claimName: group-data
status: 
  replicas: 1
