apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # creationTimestamp: null
  labels:
    io.kompose.service: group-data
  name: group-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
